### ISSUE TITLE
Use polars for file IO where possible

### ISSUE THREAD

**Issue by mmwinther** [statisticsnorway/dapla-toolbelt-pseudo#227]
Polars Dataframe is now the standard internal data representation for `dapla-toolbelt-pseudo` because it is more performant than Pandas.

Polars supports IO for:
- [CSV](https://pola-rs.github.io/polars-book/user-guide/io/csv/)
- [Parquet](https://pola-rs.github.io/polars-book/user-guide/io/parquet/)

We should use Polars where we can.

**Comment by Andilun** [comment]
Polars IO support was only added for [Parquet](https://pola-rs.github.io/polars-book/user-guide/io/parquet/) was added. See #244 for more information.
